CREATE TABLE t_equipamentos (
                                id_equip       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nm_equipamento VARCHAR2(200) NOT NULL,
                                tipo           VARCHAR2(50)  NOT NULL,
                                t_setor_id_set NUMBER        NOT NULL,
                                CONSTRAINT FK_equip_setor FOREIGN KEY (t_setor_id_set)
                                    REFERENCES t_setor (id_set)
);
