CREATE TABLE t_limite
(
    id_lmt                  NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lt_consumo              DECIMAL NOT NULL,
    hr_inicio               TIMESTAMP,
    hr_fim                  TIMESTAMP,
    t_equipamentos_id_equip NUMBER(38, 0)                                  NOT NULL,
    CONSTRAINT pk_t_limite PRIMARY KEY (id_lmt)
);


ALTER TABLE t_limite
    ADD CONSTRAINT FK_T_LIMITE_ON_T_EQUIPAMENTOS_ID_EQUIP FOREIGN KEY (t_equipamentos_id_equip) REFERENCES t_equipamentos (id_equip);

