CREATE TABLE t_logs (
    id_log       INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    log_mensagem VARCHAR2(255) NOT NULL,
    data_inc     DATE DEFAULT SYSDATE NOT NULL,
    tempo_inc    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT t_logs_pk PRIMARY KEY (id_log)
);